# Fruit Detection with Machine Learning (Python)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
path='fruits_data/'
fruits_path=[]
for root,folder,files in os.walk(path):
    for file in files:
        fruits_path.append(root+'/'+file)

In [4]:
fruits_path

['fruits_data/Apple/0_100.jpg',
 'fruits_data/Apple/100_100.jpg',
 'fruits_data/Apple/101_100.jpg',
 'fruits_data/Apple/102_100.jpg',
 'fruits_data/Apple/103_100.jpg',
 'fruits_data/Apple/104_100.jpg',
 'fruits_data/Apple/105_100.jpg',
 'fruits_data/Apple/106_100.jpg',
 'fruits_data/Apple/107_100.jpg',
 'fruits_data/Apple/108_100.jpg',
 'fruits_data/Apple/109_100.jpg',
 'fruits_data/Apple/10_100.jpg',
 'fruits_data/Apple/110_100.jpg',
 'fruits_data/Apple/111_100.jpg',
 'fruits_data/Apple/112_100.jpg',
 'fruits_data/Apple/113_100.jpg',
 'fruits_data/Apple/114_100.jpg',
 'fruits_data/Apple/115_100.jpg',
 'fruits_data/Apple/116_100.jpg',
 'fruits_data/Apple/117_100.jpg',
 'fruits_data/Apple/118_100.jpg',
 'fruits_data/Apple/119_100.jpg',
 'fruits_data/Apple/11_100.jpg',
 'fruits_data/Apple/120_100.jpg',
 'fruits_data/Apple/121_100.jpg',
 'fruits_data/Apple/122_100.jpg',
 'fruits_data/Apple/123_100.jpg',
 'fruits_data/Apple/124_100.jpg',
 'fruits_data/Apple/125_100.jpg',
 'fruits_data/Appl

In [5]:
fruits_array=[]
for img in fruits_path:
    image=cv2.imread(img)
    image=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    fruits_array.append(image)

In [6]:
fruits_array=np.asarray(fruits_array)
fruits_array.shape

(1421, 100, 100)

In [7]:
np.save('FRUITS.npy',fruits_array)

In [8]:
train_data= np.load('FRUITS.npy')
train_data

array([[[254, 254, 255, ..., 255, 255, 255],
        [254, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[254, 254, 255, ..., 255, 255, 255],
        [254, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[253, 254, 254, ..., 255, 255, 255],
        [253, 254, 255, ..., 255, 255, 255],
        [254, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       ...,

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255

In [9]:
train_data.shape

(1421, 100, 100)

In [10]:
labels= os.listdir('fruits_data')
labels

['Apple', 'Banana', 'Orange']

In [11]:
labelname= {i : labels[i] for i in range(len(labels))}
labelname

{0: 'Apple', 1: 'Banana', 2: 'Orange'}

In [12]:
label_len =[]
for root,folder,files in os.walk('fruits_data'):
    label_len.append(len(files))

In [13]:
label_len

[0, 492, 450, 479]

In [14]:
output_labels= np.zeros((len(train_data),1))
slice_1=0
slice_2=0
for i in range(len(label_len)-1):
    slice_1 += label_len[i]
    slice_2 += label_len[i+1]
    print(slice_1,slice_2)
    output_labels[slice_1:slice_2,:]=i

0 492
492 942
942 1421


In [15]:
output_labels

array([[0.],
       [0.],
       [0.],
       ...,
       [2.],
       [2.],
       [2.]])

In [16]:
def distance(x2,x1):
    return np.sqrt(sum((x1 - x2) ** 2))

def knn(x,train,k=5):
    n = train.shape[0]
    d = []
    for i in range(n):
        d.append(distance(x,train[i]))
    d = np.asarray(d)
    indexes = np.argsort(d)[:k]
    sortedLabels = output_labels[indexes]
    count = np.unique(sortedLabels, return_counts=True)
    return count[0][np.argmax(count[1])]

In [17]:
test_img= cv2.imread('156_100.jpg')

In [18]:
test_img = cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_img

array([[253, 253, 253, ..., 255, 255, 255],
       [253, 253, 254, ..., 255, 255, 255],
       [253, 254, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [19]:
test_img.shape

(100, 100)

In [20]:
test_img = cv2.resize(test_img, (100,100))

In [21]:
train_data=train_data.reshape(train_data.shape[0],-1)

In [22]:
train_data.shape

(1421, 10000)

In [23]:
label = knn(test_img.flatten(), train_data)
labelname[int(label)]

'Apple'

:)  ......  :) .......  :)  ......  :) .......  :)  ......  :) .......  :)  ......  :) .......  :)  ......  :) .......  :)  ......  :) .......  :)  ......  :) ....... :)  ......  :) .......  :)  ......  :) .......  :)  ......  :)                                               